export const DEFAULT_CLOUD_OPACITY = 0.45
export const CLOUD_REQUEST_TIMEOUT_MS = 12_000
export const CLOUD_STALE_THRESHOLD_MINUTES = 35
export const CLOUD_STALE_THRESHOLD_MS =
  CLOUD_STALE_THRESHOLD_MINUTES * 60 * 1000

export const CLOUD_IMAGE_MAX_WIDTH = 1600
export const CLOUD_IMAGE_MAX_HEIGHT = 1200
export const CLOUD_IMAGE_MAX_PIXEL_RATIO = 1.5

export const SATELLITE_HISTORY_HOURS = 3
export const SATELLITE_HISTORY_MAX_FRAMES = 20
export const SATELLITE_HISTORY_QUERY_RECORDS = 30
export const SATELLITE_PLAYBACK_INTERVAL_MS = 1_500
